import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

const pkgPath = resolve(__dirname, '../package.json');
const versionFilePath = resolve(__dirname, '../src/version.ts');

interface PackageJson {
  version: string;
}

const pkg: PackageJson = JSON.parse(readFileSync(pkgPath, 'utf8'));
const version = pkg.version;

const content = `// This file is auto-generated by scripts/sync-version.ts\nexport const version = '${version}';\n`;

writeFileSync(versionFilePath, content);
console.log(`Synced version ${version} to src/version.ts`); 